package com.shadhinpay.common.error;

public enum ErrorCode {
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  RESOURCE_NOT_FOUND,
  RESOURCE_ALREADY_EXISTS,
  INVALID_OPERATION_STATE,
  INSUFFICIENT_FUNDS,
  IDEMPOTENCY_CONFLICT,
  MFS_ADAPTER_FAILURE,
  VENDOR_DOWN,
  QUOTA_EXCEEDED,
  RISK_REJECTED,
  TOKEN_EXPIRED,
  INTERNAL_ERROR
}
